#!/bin/bash
#SBATCH --ntasks-per-node=4 
#SBATCH --mem 32000 # 32GB solicitados.
#SBATCH -p mlow # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir RTX 3090
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written

# Enable verbose mode to see commands being executed
set -x

# Python unbuffered output
export PYTHONUNBUFFERED=1

# Add some basic logging
echo "Job started at: $(date)"
echo "Running on node: $(hostname)"

python3 main.py \
    -t infer -i /ghome/c3mcv02/mcv-c5-team1/data/testing/0000/000000.png  \
    -c COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml \
    -w /ghome/c3mcv02/mcv-c5-team1/week1/src/detectron/output/train/model_final.pth -s 0.5 \
    -o /ghome/c3mcv02/mcv-c5-team1/week1/src/detectron/output/eval_finetuned

echo "Job finished at: $(date)"